(()=>{"use strict";const a=document.querySelector("[data-market-preview]");if(!a)return;const s=a.querySelector("[data-market-window]"),k=a.querySelector("[data-market-mount]"),h=a.querySelector("[data-market-loading]"),w=a.querySelector("[data-market-loading-copy]"),l=new URL("backerdemo.html#trades",document.baseURI).href;let u=!1;function p(){if(u)return;u=!0,s.setAttribute("aria-busy","true");const r=document.createElement("iframe");r.className="p2m-frame",r.title="Backer Market preview. Scroll to explore; click to enter the full market.",r.tabIndex=-1,r.loading="eager",r.referrerPolicy="strict-origin-when-cross-origin";let n,c;const i=()=>{s.setAttribute("aria-busy","false"),w.textContent="The market preview could not load. Open Backer Market directly."},m=e=>{e.preventDefault(),e.stopImmediatePropagation(),window.location.assign(l)};r.addEventListener("error",i),r.addEventListener("load",()=>{let e;try{e=r.contentDocument}catch{i();return}if(!e||!e.body){i();return}try{const f=e.createElement("style");f.textContent=`
          html{height:100%!important;overflow-y:auto!important;overscroll-behavior-y:contain;scroll-behavior:auto!important}
          body{min-height:100%!important;overflow:visible!important;cursor:pointer!important}
          .nav,.dock,[data-backer-dock],.backer-dock{display:none!important}
          .app{padding-top:18px!important;padding-bottom:35px!important}
          .mkt{padding:0 0 30px!important}
          .mkt-header{display:none!important}
          @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important}}
        `,e.head.appendChild(f);let o=null,d=!1;e.addEventListener("pointerdown",t=>{o={x:t.clientX,y:t.clientY,id:t.pointerId},d=!1},{capture:!0,passive:!0}),e.addEventListener("pointermove",t=>{!o||o.id!==t.pointerId||Math.hypot(t.clientX-o.x,t.clientY-o.y)>9&&(d=!0)},{capture:!0,passive:!0}),e.addEventListener("pointercancel",()=>{d=!0,o=null},{capture:!0,passive:!0}),e.addEventListener("click",t=>{t.preventDefault(),t.stopImmediatePropagation();const b=e.getSelection();if(d||b&&!b.isCollapsed){o=null;return}o=null,window.location.assign(l)},!0),e.addEventListener("submit",m,!0),e.addEventListener("keydown",t=>{(t.key==="Enter"||t.key===" "&&t.target.closest("button,a,input,select,textarea"))&&m(t)},!0);const y=()=>{try{if(e.querySelector(".mkt-fatal, .mkt-empty.is-error")){i(),n&&n.disconnect();return}if(!e.querySelector("#app .mkt .mkt-catalog-card"))return;s.classList.add("is-ready"),s.setAttribute("aria-busy","false"),h.hidden=!0,window.clearTimeout(c),n&&n.disconnect()}catch{i(),n&&n.disconnect()}};n=new MutationObserver(y),n.observe(e.body,{childList:!0,subtree:!0}),y()}catch{i(),n&&n.disconnect()}}),c=window.setTimeout(i,25e3),r.src=l,k.appendChild(r)}if("IntersectionObserver"in window){const r=new IntersectionObserver(n=>{n.some(c=>c.isIntersecting)&&(r.disconnect(),p())},{rootMargin:"400px 0px",threshold:.01});r.observe(a)}else p()})();
