/* Public teaching scene. Gateway Flow's cubic paths/pulse pattern is adapted to
   explicit signal delivery; all 100 profiles and coefficients are synthetic. */
(function () {
'use strict';
var scene=document.getElementById('population-scene');if(!scene)return;
function tr(value){return window.BackerI18n?window.BackerI18n.t(value):value;}
var NS='http://www.w3.org/2000/svg',reduced=matchMedia('(prefers-reduced-motion: reduce)');
var state={stage:0,reach:65,time:4,friction:40,capacity:5,access:[true,true,true],barriers:[true,true,true],selected:null};
var colors=['#f5f3ee','#c5bcb0','#e9bd86'],thresholds=[.20,.35,.50],names=['A','B','C'];
var profiles=Array.from({length:100},function(_,i){return{id:i,group:i<40?0:i<70?1:2,exposure:(((i*37)%100)+.5)/100,strength:.7+.3*((i*17)%101)/101,willingness:(((i*29+13)%101)+.5)/101,x:0,y:0};});
var allocation=document.getElementById('allocation-detail'),instrument=scene.closest('.story-instrument');
var points=document.getElementById('scene-points'),objects=document.getElementById('scene-objects'),frame=0,runFrame=0,emission=1,clockRunning=false,playing=false,visible=false,manualUntil=0,sceneWidth=700,mobile=false,lastObjectsHTML='';
function svg(tag,attrs){var n=document.createElementNS(NS,tag);Object.keys(attrs||{}).forEach(function(k){n.setAttribute(k,attrs[k]);});return n;}
profiles.forEach(function(p){var g=svg('g',{class:'population-point','data-profile':p.id,role:'button',tabindex:p.id===0?'0':'-1','aria-label':'Follow synthetic profile '+(p.id+1)}),halo=svg('circle',{r:10,fill:'none',stroke:colors[p.group],'stroke-width':1,class:'point-ring'}),core=svg('circle',{r:4,fill:colors[p.group],class:'point-core'}),hit=svg('circle',{r:12,fill:'transparent',class:'point-hit'});g.append(halo,core,hit);points.append(g);p.element=g;p.dot=core;p.ring=halo;});
function evaluate(){var groups=[0,0,0],exposed=0,considered=0,acted=0;profiles.forEach(function(p){p.noticed=state.access[p.group]&&p.exposure<state.reach/100;p.memory=p.noticed?p.strength*Math.pow(.86,state.time):0;p.considering=p.memory>=thresholds[p.group];p.acting=p.considering&&p.willingness>=state.friction/100;exposed+=+p.noticed;considered+=+p.considering;acted+=+p.acting;groups[p.group]+=+p.acting;});var units=groups.map(function(n,g){return n*[1,2,state.capacity][g];});return{exposed:exposed,considered:considered,acted:acted,groups:groups,units:units,committed:units.reduce(function(a,b){return a+b;},0),available:400};}
function t(x,y,value,cls,anchor){return'<text x="'+x+'" y="'+y+'" class="'+(cls||'scene-label')+'" text-anchor="'+(anchor||'middle')+'">'+tr(value)+'</text>';}
function curve(x0,y0,x1,y1){return'M'+x0+' '+y0+' C'+(mobile?x0:x0+(x1-x0)*.48)+' '+(mobile?y0+(y1-y0)*.48:y0)+', '+(mobile?x1:x0+(x1-x0)*.58)+' '+(mobile?y0+(y1-y0)*.55:y1)+', '+x1+' '+y1;}
function bezier(q,a,b,c,d){var u=1-q;return{x:u*u*u*a.x+3*u*u*q*b.x+3*u*q*q*c.x+q*q*q*d.x,y:u*u*u*a.y+3*u*u*q*b.y+3*u*q*q*c.y+q*q*q*d.y};}
function action(id,label,body,extra){return'<g class="scene-object" data-scene-action="'+id+'" role="button" tabindex="0" aria-label="'+tr(label)+'" '+(extra||'')+'>'+body+'</g>';}
function circleAction(id,x,y,label,glyph){return action(id,label,'<circle cx="'+x+'" cy="'+y+'" r="25" fill="#191613" stroke="#e9bd86"/><circle cx="'+x+'" cy="'+y+'" r="31" fill="none" stroke="#91663d" opacity=".24"/>'+t(x,y+6,glyph,'scene-glyph'));}
function syncReadout(r){var sums=[[r.exposed,'profiles encountered the signal'],[r.considered,'profiles remain in consideration'],[r.acted,'profiles choose to act'],[r.committed,'resource units committed']];document.getElementById('story-value').textContent=sums[state.stage][0];document.getElementById('story-unit').textContent=tr(sums[state.stage][1]);document.getElementById('story-secondary').textContent=tr('of 100 illustrative profiles · '+r.acted+' choices');scene.dataset.exposed=r.exposed;scene.dataset.considered=r.considered;scene.dataset.acted=r.acted;scene.dataset.committed=r.committed;scene.dataset.available=r.available;scene.dataset.stage=state.stage;scene.dataset.time=state.time;scene.dataset.capacity=state.capacity;scene.dataset.emitting=emission<1;document.getElementById('population-scene-desc').textContent=tr(sums[state.stage].join(' ')+'. '+r.exposed+' exposed, '+r.considered+' considering, '+r.acted+' acting. Select a point to follow its path.');['reach','time','capacity'].forEach(function(n){var input=document.getElementById('story-'+n);if(document.activeElement!==input)input.value=Number(state[n].toFixed(1));});document.getElementById('story-reach-value').textContent=state.reach+'%';document.getElementById('story-time-value').textContent=tr(state.time.toFixed(1)+' days');document.getElementById('story-friction-value').textContent=state.friction+' / 100';document.getElementById('story-capacity-value').textContent=tr(state.capacity+' units / profile');}
function profileReading(){var el=document.getElementById('story-follow');if(state.selected===null){el.innerHTML='<p>'+tr('Select a point to trace its decision.')+'</p>';return;}var p=profiles[state.selected],reason=!p.noticed?'No encounter':!p.considering?'Memory below threshold':!p.acting?'Friction exceeds willingness':'Acts on the option',units=p.acting?[1,2,state.capacity][p.group]:0;var reading=tr(reason+' · memory '+p.memory.toFixed(2)+' / threshold '+thresholds[p.group].toFixed(2)+' · '+units+(units===1?' unit committed':' units committed'));el.innerHTML='<div><strong>'+tr('Profile '+String(p.id+1).padStart(2,'0'))+' <span>'+tr('· Group '+names[p.group])+'</span></strong><p>'+reading+'</p></div><div class="profile-arrows"><button type="button" data-profile-prev aria-label="'+tr('Follow previous profile')+'">←</button><button type="button" data-profile-next aria-label="'+tr('Follow next profile')+'">→</button></div>';}

function syncAllocation(r){
  allocation.hidden=state.stage!==3;
  instrument.dataset.stage=state.stage;
  if(state.stage!==3)return;
  allocation.querySelectorAll('[data-allocation-group]').forEach(function(group,j){
    var capacity=[1,2,state.capacity][j];
    group.querySelector('[data-allocation-units]').textContent=r.units[j];
    group.querySelector('[data-allocation-formula]').textContent=tr(r.groups[j]+' acting × '+capacity+(capacity===1?' unit each':' units each'));
  });
  var reserve=10-state.capacity;
  document.getElementById('allocation-reserve-count').textContent=tr(reserve+(reserve===1?' parcel available':' parcels available'));
  document.getElementById('allocation-total').textContent=r.committed;
  document.getElementById('allocation-actors').textContent=tr(r.acted+(r.acted===1?' profile acting':' profiles acting'));
  document.getElementById('allocation-add').disabled=reserve===0;
  document.getElementById('allocation-return').disabled=state.capacity===1;
}
function draw(){mobile=scene.clientWidth<560;var stage=state.stage;sceneWidth=stage===3?scene.clientWidth:(mobile?360:700);scene.setAttribute('viewBox','0 0 '+sceneWidth+' '+(stage===3?220:(mobile?490:450)));var r=evaluate(),g='',o='',links='',centers=stage===3?[sceneWidth/6,sceneWidth/2,sceneWidth*5/6]:(mobile?[60,180,300]:[245,410,575]),source={x:mobile?180:49,y:mobile?45:210},active=0,inactive=0;
var titles=['Launch a signal.','Let memory fade.','Remove a barrier.','Redistribute capacity.'];
var hints=['Click the signal to send it. Tap a channel to close or reopen access.','Tap the clock to play time. Send a reminder to refresh the encounter.','Tap a barrier to remove it. Profiles cross into action.','Bright dots act; dim dots defer. Larger dots have more capacity.'];
if(stage===0){o+=circleAction('launch',source.x,source.y,'Launch a signal','↗');g+=t(source.x,source.y+(mobile?46:51),'SEND','scene-meta');centers.forEach(function(x,j){var y=mobile?117:49;o+=action('channel-'+j,(state.access[j]?'Close':'Open')+' channel '+names[j],'<rect x="'+(x-41)+'" y="'+(y-21)+'" width="82" height="42" rx="21" fill="'+(state.access[j]?'#241d16':'#111')+'" stroke="'+(state.access[j]?'#b88953':'#51463c')+'"/>'+t(x,y+4,names[j]+' · '+(state.access[j]?'open':'closed'),'scene-label'));});g+=t(sceneWidth/2,mobile?459:419,r.exposed+' encounters · '+(100-r.exposed)+' beyond reach','scene-total');}
if(stage===1){var cx=sceneWidth/2,cy=mobile?43:36;o+=circleAction('clock',cx,cy,clockRunning?'Pause elapsed time':'Play elapsed time',clockRunning?'Ⅱ':'▷');g+=t(cx,cy+49,'DAY '+state.time.toFixed(1),'scene-meta');o+=action('remind','Send a reminder','<rect x="'+(sceneWidth-114)+'" y="'+(mobile?12:11)+'" width="105" height="45" rx="22" fill="#1d1813" stroke="#876b48"/>'+t(sceneWidth-62,mobile?40:39,'Remind ↗','scene-label'));g+=t(sceneWidth/2,mobile?460:420,r.considered+' still considering · '+r.exposed+' encountered','scene-total');}
if(stage===2){var labels=['Setup','Time','Habit'],xs=mobile?[60,180,300]:[190,350,510];xs.forEach(function(x,j){o+=action('barrier-'+j,(state.barriers[j]?'Remove ':'Restore ')+labels[j]+' barrier','<rect x="'+(x-(mobile?49:63))+'" y="19" width="'+(mobile?98:126)+'" height="47" rx="5" fill="'+(state.barriers[j]?'#241e18':'#111')+'" stroke="'+(state.barriers[j]?'#c6975e':'#54483b')+'" stroke-dasharray="'+(state.barriers[j]?'0':'4 5')+'"/>'+t(x,48,labels[j]+' '+(state.barriers[j]?'×':'+'),'scene-label'));});g+=t(mobile?90:197,109,r.acted+' act','scene-destination')+t(mobile?270:515,109,(100-r.acted)+' defer','scene-destination');g+='<line x1="'+sceneWidth/2+'" x2="'+sceneWidth/2+'" y1="126" y2="380" stroke="#665440" stroke-dasharray="2 7"/>';g+=t(sceneWidth/2,mobile?460:421,'Friction '+state.friction+' / 100 · '+r.considered+' in consideration','scene-total');}
if(stage===3){centers.forEach(function(x,j){g+=t(x,22,'GROUP '+names[j],'scene-meta');});}
profiles.forEach(function(p){var j=p.id-[0,40,70][p.group],c=centers[p.group],x,y,opacity=1,rad=mobile?3.4:4,ring=0,selected=state.selected===p.id;
if(stage===0||stage===1){x=c+(j%4-1.5)*(mobile?18:28);y=(mobile?165:109)+Math.floor(j/4)*(mobile?28:30);if(stage===0){var arrival=.1+p.exposure/Math.max(.01,state.reach/100)*.82;opacity=p.noticed&&emission>=arrival?1:.13;if(p.noticed){var d=curve(source.x,source.y,x,y);links+='<path d="'+d+'" fill="none" stroke="'+colors[p.group]+'" opacity="'+(selected?.36:.055)+'" stroke-width="'+(selected?1.5:.8)+'"/>';if(emission<1){var q=Math.min(1,Math.max(0,(emission-(j%8)*.012)/.85)),a=source,b={x:mobile?source.x:source.x+(x-source.x)*.48,y:mobile?source.y+(y-source.y)*.48:source.y},cc={x:mobile?x:source.x+(x-source.x)*.58,y:mobile?source.y+(y-source.y)*.55:y},z=bezier(q,a,b,cc,{x:x,y:y});links+='<circle cx="'+z.x+'" cy="'+z.y+'" r="'+(selected?3:1.8)+'" fill="'+colors[p.group]+'" opacity="'+(q<1?.8:0)+'"/>';}}}else{opacity=p.noticed?.2+.8*p.memory:.09;rad=(mobile?2.5:3)+3*p.memory;ring=p.considering?.65:0;}}
else if(stage===2){var k=p.acting?active++:inactive++,columns=mobile?6:8;x=(p.acting?(mobile?42:102):(mobile?222:420))+(k%columns)*(mobile?19:25);y=151+Math.floor(k/columns)*(mobile?13:19);opacity=p.acting?1:p.considering?.45:.10;ring=p.acting?.23:0;}
else{x=c+(j%4-1.5)*(mobile?18:28);y=42+Math.floor(j/4)*19;rad=(mobile?2.5:3)*Math.sqrt([1,2,state.capacity][p.group]);opacity=p.acting?1:.12;}
p.x=x;p.y=y;p.element.style.transform='translate('+x+'px,'+y+'px)';p.element.classList.toggle('is-followed',selected);p.dot.setAttribute('r',rad);p.dot.style.opacity=selected?1:opacity;p.ring.setAttribute('r',selected?rad+7:rad+4);p.ring.style.opacity=selected?1:ring;p.element.setAttribute('aria-pressed',selected);p.element.setAttribute('aria-label','Profile '+(p.id+1)+', group '+names[p.group]+', '+(!p.noticed?'no encounter':!p.considering?'memory below threshold':p.acting?'acts':'defers'));
});
var focused=document.activeElement&&document.activeElement.dataset.sceneAction;document.getElementById('scene-guides').innerHTML=g;document.getElementById('scene-links').innerHTML=links;if(o!==lastObjectsHTML){objects.innerHTML=o;lastObjectsHTML=o;}
if(focused){var replacement=objects.querySelector('[data-scene-action="'+focused+'"]');if(replacement)replacement.focus({preventScroll:true});}
var trail=document.getElementById('scene-trail');if(state.selected!==null){var p=profiles[state.selected];trail.innerHTML=stage===3?'':'<path d="'+curve(mobile?26:38,mobile?440:409,p.x,p.y)+'" stroke="#e9bd86" fill="none" stroke-width="1" stroke-dasharray="3 6" opacity=".4"/>'+t(mobile?29:40,mobile?453:427,'#'+String(p.id+1).padStart(2,'0'),'scene-meta');}else trail.replaceChildren();
document.getElementById('story-figure-title').textContent=tr(titles[stage]);document.getElementById('story-caption').textContent=tr(stage===3&&r.groups[2]===0?'No C profiles act in this state, so added capacity stays unused. Send a reminder in Memory to change consideration.':hints[stage]);syncReadout(r);syncAllocation(r);profileReading();
}
function cancelMotion(){cancelAnimationFrame(frame);frame=0;clockRunning=false;emission=1;}
function stopPath(){cancelAnimationFrame(runFrame);runFrame=0;playing=false;document.getElementById('story-play').innerHTML='Play the sequence <span aria-hidden="true">↗</span>';}
function manual(){stopPath();cancelMotion();manualUntil=performance.now()+1400;}
function launch(){cancelMotion();emission=0;if(reduced.matches){emission=1;draw();return;}var start=performance.now();function tick(now){emission=Math.min(1,(now-start)/1250);draw();if(emission<1&&visible&&!document.hidden)frame=requestAnimationFrame(tick);else{emission=1;frame=0;draw();}}frame=requestAnimationFrame(tick);}
function runClock(limit){limit=limit||14;if(clockRunning){cancelMotion();draw();return;}cancelMotion();if(state.time>=limit)state.time=0;if(reduced.matches){state.time=Math.min(limit,state.time+3);draw();return;}clockRunning=true;var start=performance.now(),from=state.time;function tick(now){state.time=Math.min(limit,from+(now-start)/520);draw();if(state.time<limit&&clockRunning&&visible&&!document.hidden)frame=requestAnimationFrame(tick);else{clockRunning=false;frame=0;draw();}}frame=requestAnimationFrame(tick);}
function selectStage(index,fromScroll){var previous=state.stage;if(!fromScroll)cancelMotion();state.stage=index;document.querySelectorAll('[data-story-stage]').forEach(function(b){b.setAttribute('aria-pressed',+b.dataset.storyStage===index);});document.querySelectorAll('[data-story-step]').forEach(function(s){s.classList.toggle('is-active',+s.dataset.storyStep===index);});draw();if(!fromScroll&&previous!==index&&innerWidth>900){manualUntil=performance.now()+1400;var step=document.querySelector('[data-story-step="'+index+'"]'),behavior=reduced.matches?'instant':'smooth';if(index===3)window.scrollTo({top:window.scrollY+step.getBoundingClientRect().bottom-instrument.offsetHeight-80,behavior:behavior});else step.scrollIntoView({block:'center',behavior:behavior});}}
function doAction(id){var wasClock=clockRunning;manual();if(id==='launch')launch();else if(id.indexOf('channel-')===0){var g=+id.slice(-1);state.access[g]=!state.access[g];launch();}else if(id==='clock'){if(!wasClock)runClock();else draw();}else if(id==='remind'){state.time=0;draw();launch();}else if(id.indexOf('barrier-')===0){var k=+id.slice(-1);state.barriers[k]=!state.barriers[k];state.friction=state.barriers.reduce(function(s,b,i){return s+(b?[20,15,5][i]:0);},0);draw();}else if(id==='allocate'){state.capacity=Math.min(10,state.capacity+1);draw();}else if(id==='return'){state.capacity=Math.max(1,state.capacity-1);draw();}}
objects.addEventListener('click',function(e){var a=e.target.closest('[data-scene-action]');if(a)doAction(a.dataset.sceneAction);});
objects.addEventListener('keydown',function(e){var a=e.target.closest('[data-scene-action]');if(a&&(e.key==='Enter'||e.key===' ')){e.preventDefault();doAction(a.dataset.sceneAction);}});
function follow(id){manual();state.selected=(id+100)%100;profiles.forEach(function(p){p.element.setAttribute('tabindex',p.id===state.selected?'0':'-1');});draw();}
points.addEventListener('click',function(e){var a=e.target.closest('[data-profile]');if(a)follow(+a.dataset.profile);});
points.addEventListener('keydown',function(e){var a=e.target.closest('[data-profile]');if(!a)return;var n=+a.dataset.profile;if(e.key==='Enter'||e.key===' '){e.preventDefault();follow(n);}else if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();n=(n+(e.key==='ArrowRight'||e.key==='ArrowDown'?1:99))%100;follow(n);profiles[n].element.focus({preventScroll:true});}});
document.getElementById('story-follow').addEventListener('click',function(e){if(e.target.closest('[data-profile-prev]'))follow(state.selected-1);if(e.target.closest('[data-profile-next]'))follow(state.selected+1);});
// Native buttons preserve keyboard and tap access; the gold parcel also supports dragging to C.
var drag=null,dragged=false,parcelButton=document.getElementById('allocation-add'),allocationTarget=allocation.querySelector('[data-allocation-group="2"]');
allocation.addEventListener('click',function(e){if(dragged){dragged=false;return;}var button=e.target.closest('[data-allocation-action]');if(button&&!button.disabled)doAction(button.dataset.allocationAction);});
parcelButton.addEventListener('pointerdown',function(e){if(parcelButton.disabled)return;manual();drag={x:e.clientX,y:e.clientY};parcelButton.setPointerCapture(e.pointerId);});
parcelButton.addEventListener('pointermove',function(e){if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6){dragged=true;parcelButton.querySelector('.allocation-parcel').style.transform='translate('+(e.clientX-drag.x)+'px,'+(e.clientY-drag.y)+'px)';allocationTarget.classList.add('is-drop-target');}});
function clearParcelDrag(){drag=null;parcelButton.querySelector('.allocation-parcel').style.transform='';allocationTarget.classList.remove('is-drop-target');}
parcelButton.addEventListener('pointerup',function(e){if(!drag)return;if(dragged){var rect=allocationTarget.getBoundingClientRect(),plot=scene.getBoundingClientRect(),onSummary=e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom,onProfiles=e.clientX>=plot.left+plot.width*2/3&&e.clientX<=plot.right&&e.clientY>=plot.top&&e.clientY<=plot.bottom;if(onSummary||onProfiles)doAction('allocate');}clearParcelDrag();setTimeout(function(){dragged=false;},0);});
parcelButton.addEventListener('pointercancel',function(){clearParcelDrag();dragged=false;});
['reach','time','capacity'].forEach(function(n){var input=document.getElementById('story-'+n);function edit(e){if(e.type==='input'&&e.target.value==='')return;manual();var value=Number(e.target.value),min=Number(e.target.min),max=Number(e.target.max);state[n]=Math.max(min,Math.min(max,Number.isFinite(value)?value:min));if(n==='capacity')state[n]=Math.round(state[n]);if(e.type==='change')e.target.value=state[n];draw();}input.addEventListener('input',edit);input.addEventListener('change',edit);});
document.querySelectorAll('[data-story-stage]').forEach(function(b){b.addEventListener('click',function(){manual();selectStage(+b.dataset.storyStage);});});
document.getElementById('story-reset').addEventListener('click',function(){manual();Object.assign(state,{reach:65,time:4,friction:40,capacity:5,access:[true,true,true],barriers:[true,true,true],selected:null});draw();});
document.getElementById('story-play').addEventListener('click',function(){if(playing){stopPath();cancelMotion();draw();return;}cancelMotion();playing=true;document.getElementById('story-play').textContent='Stop playback ■';var start=performance.now(),last=-1;function tick(now){if(!playing)return;var index=Math.min(3,Math.floor((now-start)/(reduced.matches?1400:2500)));if(index!==last){last=index;selectStage(index);if(index===0)launch();if(index===1){state.time=0;runClock(3);}if(index===2){cancelMotion();state.barriers=[false,true,true];state.friction=20;draw();}}if(now-start<(reduced.matches?6000:11000)&&visible&&!document.hidden)runFrame=requestAnimationFrame(tick);else{stopPath();cancelMotion();draw();}}runFrame=requestAnimationFrame(tick);});
var queued=false;function onScroll(){if(queued||!visible||innerWidth<=900||playing||clockRunning||frame||performance.now()<manualUntil)return;queued=true;requestAnimationFrame(function(){queued=false;var center=innerHeight*.52,closest=0,distance=Infinity;document.querySelectorAll('[data-story-step]').forEach(function(s,i){var b=s.getBoundingClientRect(),d=Math.abs((b.top+b.bottom)/2-center);if(d<distance){distance=d;closest=i;}});if(closest!==state.stage)selectStage(closest,true);});}
if('IntersectionObserver'in window){var first=true;new IntersectionObserver(function(entries){visible=entries[0].isIntersecting;if(visible){if(first){first=false;launch();}onScroll();}else{cancelMotion();stopPath();draw();}},{threshold:.15}).observe(scene);window.addEventListener('scroll',onScroll,{passive:true});}else visible=true;
document.addEventListener('visibilitychange',function(){if(document.hidden){cancelMotion();stopPath();draw();}});reduced.addEventListener('change',function(){cancelMotion();stopPath();draw();});window.addEventListener('resize',draw);selectStage(0);
}());
