#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const source = require.resolve('cobe');
const destination = path.join(root, 'js', 'vendor', 'cobe.mjs');
const banner = [
  '/*! COBE v2.0.1 | Copyright (c) 2021 Shu Ding | MIT License */',
  '/* Generated by scripts/vendor-cobe.js. Do not edit directly. */',
  ''
].join('\n');

fs.mkdirSync(path.dirname(destination), { recursive: true });
fs.writeFileSync(destination, banner + fs.readFileSync(source, 'utf8'));
process.stdout.write(`Vendored COBE to ${path.relative(root, destination)}\n`);
